<?php

$langs = [
	
	'_ABDULLAH_SULAIMAN_ALBLOUI_' => ['شركة عبدالله سليمان البلوي العقارية', 'Abdullah Sulaiman Albloui Realestate Company'],
	'_ABDULLAH_SULAIMAN_ALBLOUI_HEADER_' => ['<span class="heading-color" >شركة</span> <b>عبدالله سليمان البلوي</b> <span class="heading-color" >العقارية</span>', 'Abdullah Sulaiman Albloui <span class="heading-color" >Realestate Company</span>'],

	// Navbar
		'_HOME_' => ['الرئيسية', 'Home', 'Ana sayfa'],
		'_REALESTATE_' => ['العقارات', 'Realestates', 'Gayrimenkul'],
		'_MORE_REALESTATE_' => ['عقارات أخرى', 'Other Realestates'],
		'_OUR_SERVICES_' => ['خدماتنا', 'Our Services', 'Hizmetlerimiz'],
			'_OUR_SERVICES_CONSULTING_' => ['الاستشارات العقارية', 'Real Estate Consulting', 'Gayrimenkul Danışmanlığı'],
			'_OUR_SERVICES_PROPERTY_MANAGEMENT_' => ['إدارة الأملاك العقارية', 'Property Management', 'Mülkiyet yönetimi'],
			'_OUR_SERVICES_REALESTATE_MARKETING_' => ['التسويق العقاري', 'Real Estate Marketing', 'Gayrimenkul Pazarlama'],
			'_OUR_SERVICES_REALESTATE_DEVELOPMENT_' => ['التطوير العقاري', 'Real Estate Development', 'Gayrimenkul Geliştirme'],
			'_OUR_SERVICES_REALESTATE_TOURS_RECEPTION_' => ['الجولات العقارية والاستقبال', 'Real Estate Tours & Reception', 'Gayrimenkul Turları ve Resepsiyon'],
		'_BLOG_' => ['المدونة', 'Blog', 'Blog'],
		'_ABOUTUS_' => ['من نحن', 'About us', 'Biz kimimiz'],
		'_CONTACT_' => ['اتصل بنا', 'Contact us', 'Bizi ulaşın'],
		'_OUR_PARTNERS_' => ['شركاؤنا', 'Our Partners', 'Ortaklarımız'],
		'_CALL_US_NOW_' => ['اتصل بنا الآن', 'Call Us Now'],

	'_FOOTER_DESC_' => [
		'تعتبر شركة الروابي للاستثمار والتطوير العقاري إحدى شركات مجموعة الروابي للعقارات والإنشاءات والسياحة والتجارة الخارجية',
		'Al Rawabi Real Estate Investment & Development Company is a member of Al Rawabi Group for Real Estate, Construction, Tourism and Foreign Trade',
		'Al Rawabi Gayrimenkul Yatırım ve Geliştirme Şirketi, Al Rawabi Gayrimenkul, İnşaat, Turizm ve Dış Ticaret Grubunun bir üyesidir'
	],

	// Properties
		'_OWNER_PHONE_' => ['هاتف مالك العقار', 'Property Onwer Phone'],
		'_OWNER_EMAIL_' => ['بريد مالك العقار', 'Property Onwer Email'],
		'_PROPERTY_NAME_' => ['اسم العقار', 'Property Name'],
		'_SELECT_PROPERTY_PHOTOS_' => ['اختر صور العقار', 'Select Property Photos'],
		'_SELECT_PROPERTY_TYPE_' => ['اختر نوع عقارك', 'Select Your Property Type'],
		'_ADVERTISE_YOUR_PROPERTY_' => ['أعلن عن عقارك', 'Advertise Your Property'],
		'_REQUEST_YOUR_PROPERTY_' => ['اطلب عقارك', 'Request a property'],
		'_ALL_PROPERTIES_' => ['جميع العقارات', 'All Properties'],
		'_REALESTATE_ID_' => ['رقم العقار'],
		'_REALESTATE_DIRECTIONS_' => ['الاتجاهات'],
		'_REALESTATE_DIRECTIONS_NORTH_' => ['شمال'],
		'_REALESTATE_DIRECTIONS_SOUTH_' => ['جنوب'],
		'_REALESTATE_DIRECTIONS_EAST_' => ['شرق'],
		'_REALESTATE_DIRECTIONS_WEST_' => ['غرب'],
		'_FEATURED_PROPERTIES_' => ['العقارات المميزة', 'Featured Properties'],
		'_SORT_BY_' => ['ترتيب حسب', 'Sort By'],
		'_QUICK_SUMMARY_' => ['تفاصيل سريعة', 'Quick Summary', ''],
		'_PROPERTY_DESCRIPTION_' => ['وصف العقار', 'Property Description', 'Emlak Açıklaması'],
		'_PROPERTY_FEATURES_' => ['مزايا العقار', 'Property Features', 'Emlak Özellikleri'],
		'_PRICE_' => ['السعر', 'Price', 'Fiyat'],
		'_MONTHLY_RENTAL_' => ['الآجار الشهري', 'Monthly Rental', 'Aylık Kirası'],
		'_CITY_' => ['المدينة', 'City', 'İl'],
		'_DISTRICT_' => ['الحي', 'District', 'İlçe'],
		'_PLAN_NAME_' => ['اسم المخطط', 'Plan Name'],
		'_PLAN_NUMBER_' => ['رقم المخطط', 'Plan Number'],
		'_RIYAL_' => ['ريال', 'Riyal'],
		'_VIDEOS_' => ['مقاطع الفيديو', 'Videos', 'Videolar'],
		'_FOR_SALE_' => ['للبيع', 'For Sale', 'Satılık'],
		'_FOR_RENT_' => ['للإيجار', 'For Rent', 'Kiralık'],
		'_SIMILAR_PROPERTIES_' => ['عقارات مشابهة', 'Similar Properties', 'Benzer Emlaklar'],
		'_LATEST_PROPERTIES_' => ['آخر العقارات', 'Latest Properties', 'En Son Gayrimenkullar'],
		'_PROPERTY_TYPE_' => ['نوع العقار', 'Property Type', 'Emalk Türü'],
		'_MARKETING_TYPE_' => ['نوع التسويق', 'Marketing Type'],
		'_SALE_' => ['بيع', 'Sale', 'Satılık'],
		'_RENT_' => ['تأجير', 'Rent', 'Kiralık'],
		'_FEATURED_PROPERTIES_' => ['عقارات مميزة', 'Featured Properties', 'Öne Çıkan Emlak'],
		'_VIEWS_' => ['المشاهدات', 'Views'],
		'_FLATS_' => ['شقق', 'Flats'],
		'_FLAT_' => ['شقة', 'Flat'],
		'_BUILDINGS_' => ['عماير', 'Buildings'],
		'_BUILDING_' => ['عمارة', 'Building'],
		'_VILLAS_' => ['فلل', 'Villas'],
		'_VILLA_' => ['فيلا', 'Villa'],
		'_LANDS_' => ['أراضي', 'Lands'],
		'_LAND_' => ['أرض', 'Land'],
		'_AGENCY_ADS_' => ['إعلانات الوكالة العقارية', 'Agency Ads'],
		'_VIEW_DETAILS_' => ['مشاهدة التفاصيل', 'View Details'],

	// Search
		'_WRITE_TEXT_' => ['اكتب شيئاً', 'Write something'],
		'_SEARCH_IN_FLATS_' => ['البحث في الشقق', 'Search in Flats'],
		'_SEARCH_IN_BUILDINGS_' => ['البحث في العماير', 'Search in Buildings'],
		'_SEARCH_IN_VILLAS_' => ['البحث في الفلل', 'Search in Villas'],
		'_SEARCH_IN_LANDS_' => ['البحث في الأراضي', 'Search in Lands'],
		'_SEARCH_RESULTS_' => ['نتائج البحث', 'Search Results', 'Arama Sonuçları'],
		'_SEARCH_YOUR_REALESTATE_' => ['ابحث عن عقارك', 'Search Your Real Estate', 'Emlak Ara'],
		'_SEARCH_NOW_' => ['ابحث', 'Search Now'],
		'_MIN_' => ['أدنى', 'Min', 'Min'],
		'_MAX_' => ['أعلى', 'Max', 'Max'],
		'_APPROXIMATE_' => ['تقريبي', 'Approximate', 'Yaklaşık'],
		'_UNKNOWN_' => ['غير معروف', 'Unknown', 'Bilinmeyen'],
		'_ROOMS_' => ['عدد الغرف', 'Rooms Number', 'Oda Sayısı'],
		'_AREA_' => ['المساحة', 'Area', 'Alan'],
		'_AREA_UNIT_' => ['م', 'm', 'm'],
		'_GROUND_AREA_' => ['مساحة الأرض'],
		'_BUILDING_AREA_' => ['مساحة البناء الفعلية'],
		'_STUDIO_' => ['استديو', 'Studio', 'Stüdyo'],
		'_ROOMS_MORE_THAN_10_' => ['فوق 10 غرف', 'More Than 10 Rooms', '10 Üzeri'],
		'_FLOOR_' => ['الطابق', 'Floor', 'Kat'],
		'_BASEMENT_' => ['طابق سفلي', 'Basement Floor', 'Bodrum Katı'],
		'_GROUND_FLOOR_' => ['طابق أرضي', 'Ground Floor', 'Zemin Katı'],
		'_GARDEN_FLOOR_' => ['طابق حديقة', 'Garden Floor', 'Bahçe Katı'],
		'_ENTRANCE_FLOOR_' => ['طابق المدخل', 'Entrance Floor', 'Giriş Katı'],
		'_HIGH_ENTRANCE_' => ['مدخل مرتفع', 'High Entrance', 'Yüksek Giriş'],
		'_SEPARATE_' => ['منفصل', 'Separate', 'Müstakil'],
		'_VILLA_TYPE_' => ['نظام فيلات', 'Villa Type', 'Villa Tipi'],
		'_ATTIC_' => ['طابق السطح', 'Attic Floor', 'Çatı Katı'],
		'_ABOVE_FLOOR_30_' => ['فوق الطابق 30', 'Above 30 Floor', '30 ve Üzeri'],
		'_BUILDING_AGE_' => ['عمر البناء', 'Building Age', 'Bina Yaşı'],
		'_ABOVE_30_YEARS_' => ['أكثر من 30 سنة', 'More Than 30 Years', '30 Üzeri'],
		'_FLOORS_' => ['عدد طوابق البناء', 'Floors Number', 'Kat Sayısı'],
		'_FLOORS_MORE_THAN_30_' => ['أكثر من 30 طابق', 'More Than 30 Floors', '30 Üzeri'],
		'_HEATING_' => ['التدفئة', 'Heating', 'Isıtma'],
		'_STOVE_' => ['مدفأة', 'Stove', 'Soba'],
		'_GAS_STOVE_' => ['مدفأة غاز', 'Gas Stove', 'Gaz Sobası'],
		'_CENTRAL_' => ['تدفئة مركزية', 'Central', 'Merkezi'],
		'_COMBI_BOILER_' => ['غاز (كومبي)', 'Combi Boiler', 'Doğalgaz (Kobmi)'],
		'_FLOOR_HEATING_' => ['تدفئة أرضية', 'Floor Heating', 'Yerden Isıtma'],
		'_AIR_CONDITIONER_' => ['مكيف هواء', 'Air Conditioner', 'Klima'],
		'_FAN_COIL_CONDITIONER_' => ['مكيف سقفي', 'Fan Coil Conditioner', 'Fancoil Ünitesi'],
		'_SLOAR_POWER_' => ['طاقة شمسية', 'Solar Power', 'Güneş Enerjisi'],
		'_GEOTHERMAL_' => ['تدفئة أرضية', 'Geothermal', 'Jeotermal'],
		'_FIREPLACE_' => ['موقد حجري', 'Fireplace', 'Şömine'],
		'_VRV_' => ['حجم التبريد المتغير (VRV)', 'VRV', 'VRV'],
		'_HEAT_PUMP_' => ['مضخة حرارة', 'Heat Pump', 'Isı Pompası'],
		'_BATHS_' => ['عدد الحمامات', 'Paths Number', 'Banyo Sayısı'],
		'_BALCONY_' => ['شرفة', 'Balcony', 'Balkon'],
		'_NO_BALCONY_' => ['لا يوجد شرفة', 'No Blacony'],
		'_THERE_IS_BALCONY_' => ['يوجد شرفة', 'There is Blacony'],
		'_FURNISHED_' => ['حالة الفرش', 'Furnished', 'Eşyalı'],
		'_NOT_FURNIESHED_' => ['غير مفروش', 'Not Furnished'],
		'_IT_IS_FURNISHED_' => ['مفروش', 'Furnished'],
		'_USING_STATUS_' => ['وضع الاستخدام', 'Using Status', 'Kullanım Durumu'],
		'_EMPTY_' => ['فارغ', 'Empty', 'Boş'],
		'_TENANTED_' => ['مؤجر', 'Tenanted', 'Kiracılı'],
		'_PROPERTY_OWNER_' => ['مالك العقار', 'Property Owner', 'Mülk Sahibi'],
		'_SITE_WITHIN_' => ['داخل مجمع سكني', 'Site Within', 'Site İçeresinde'],
		'_YES_' => ['نعم', 'Yes', 'Evet'],
		'_NO_' => ['لا', 'No', 'Hayır'],

	// Contact us
		'_CALL_NOW_' => ['اتصل الآن', 'Call Now'],
		'_NAME_' => ['الاسم', 'Name', 'Ad'],
		'_EMAIL_' => ['البريد الالكتروني', 'Email', 'E-posta'],
		'_PHONE_' => ['رقم الهاتف', 'Phone', 'Telefon'],
		'_MOBILE_' => ['جوال', 'Mobile', 'Cep telefon'],
		'_FAX_' => ['فاكس', 'Fax', 'Fax'],
		'_SUBJECT_' => ['الموضوع', 'Subject', 'Konu'],
		'_MESSAGE_' => ['الرسالة', 'Message', 'Mesaj'],
		'_FOLLOW_US_ON_SOCIAL_MEDIA_' => ['تابعنا على شبكات التواصل', 'Follow us on social media', 'Sosyal medyada bizi takip edin'],
		'_WHATSAPP_' => ['واتس آب', 'Whatsapp', 'Whatsapp'],
		'_ADDRESS_' => ['العنوان', 'Address', 'Adres'],
		'_PLEASE_WAIT_' => ['يرجى الإنتظار', 'Please wait', 'Lütfen bekleyin'],
		'_OUR_LOCATION_' => ['موقعنا', 'Our location', 'Konumumuz'],
		'_USEFUL_LINKS_' => ['روابط مفيدة', 'Useful Links', 'Kullanışlı Bağlantılar'],
		'_SEND_US_A_MESSAGE_' => ['أرسل لنا رسالة', 'Send us a message', 'Bize mesaj atınız'],
		'_MESSAGE_SENT_' => ['تم إرسال رسالتك بنجاح, شكراً لتواصلكم معنا', 'Your Message was sent successfully, thank you for contacting us', 'Mesajınız gönderdi, Bizimle iletişime geçtiğiniz için teşekkürler'],
		'_MESSAGE_NOT_SENT_' => ['لم يتم إرسال رسالتكم, يرجى المحاولة لاحقاً', 'Message was not sent, please try again later', 'Mesajınız göndermedi, lütefn daha sonra tekrar deneyiniz'],


	// Login
		'_LOGIN_' => ['تسجيل الدخول', 'Login'],

	// Working hours
		'_WORKING_HOURS_' => ['أوقات العمل', 'Working hours', 'Çalışma saatleri'],
		'_OFFICIAL_HOLIDAY_' => ['عطلة رسمية', 'Official holiday', 'Resmi tatil'],

	// Languages
		'_ARABIC_' => ['العربية', 'العربية', 'العربية'],
		'_ENGLISH_' => ['English', 'English', 'English'],
		'_TURKISH_' => ['Türkçe', 'Türkçe', 'Türkçe'],

	// Months
		'_JAN_' => ['كانون الثاني', 'January', 'Ocak'],
		'_FEB_' => ['شباط', 'February', 'Şubat'],
		'_MAR_' => ['آذار', 'March', 'Mart'],
		'_APR_' => ['نسيان', 'April', 'Nisan'],
		'_MAY_' => ['أيار', 'May', 'Mayıs'],
		'_JUN_' => ['حزيران', 'June', 'Haziran'],
		'_JUL_' => ['تموز', 'July', 'Temmuz'],
		'_AUG_' => ['آب', 'August', 'Ağustos'],
		'_SEP_' => ['أيلول', 'September', 'Eylül'],
		'_OCT_' => ['تشرين الأول', 'October', 'Ekim'],
		'_NOV_' => ['تشرين الثاني', 'November', 'Kasım'],
		'_DEC_' => ['كانون الأول', 'December', 'Aralık'],

	// Days
		'_DAY_' => ['اليوم', 'Day', 'Gün'],
		'_MONDAY_' => ['الإثنين', 'Monday', 'Pazartesi'],
		'_TUESDAY_' => ['الثلاثاء', 'Tuesday', 'Salı'],
		'_WEDNESDAY_' => ['الأربعاء', 'Wednesday', 'Çarşamba'],
		'_THURSDAY_' => ['الخميس', 'Thursday', 'Perşembe'],
		'_FRIDAY_' => ['الجمعة', 'Friday', 'Cuma'],
		'_SATURDAY_' => ['السبت', 'Saturday', 'Cumartesi'],
		'_SUNDAY_' => ['الأحد', 'Sunday', 'Pazar'],

	'_COPYRIGHT_' => [
		'حقوق النشر &copy; ' . date('Y', time()) . ' شركة الروابي العقارية',
		'Copyright &copy;' . date('Y', time()) . ' Al-rawabi Real Estates',
		'Telif hakkı &copy;' . date('Y', time()) . ' Al-rawabi Emlak'
	],
	'_ALL_RIGHTS_RESERVED_' => ['جميع الحقوق محفوظة', 'All rights reserved', 'Tüm hakkları saklıdır'],
	'_ALRAWI_' => ['شركة الراوي', 'Al-rawi Company', 'Al-rawi Şirketi'],
	'_ALRAWI_COPYRIGHT_' => [
		'تصميم وتطوير شركة <a href="https://www.alrawi.co" target="_blank" ><u>الراوي</u></a>',
		'Designed & developed by <a href="https://www.alrawi.co" target="_blank" ><u>Alrawi</u></a> company',
		'<a href="https://www.alrawi.co" target="_blank" ><u>Alrawi</u></a> şirketi tarafından tasarlandı ve geliştirildi',
	],
	'_MESSAGE_WAS_SENT_' => ['لقد تم ارسال رسالتك', 'Your message has been sent successfully', 'Mesajın başarıyla göderildi'],
	'_MORE_' => ['المزيد', 'More', 'Daha'],
	'_LAT_' => ['خط العرض'],
	'_LNG_' => ['خط الطول'],
	'_DATE_' => ['التاريخ'],
	'_SAVE_' => ['حفظ'],
	'_CANCEL_' => ['الغاء'],
	'_LANG_' => ['اللغة', 'Language', 'Dil'],
	'_REFRESH_' => ['تحديث'],
	'_SEND_' => ['ارسال', 'Send', 'Gönder'],
	'_PRINT_' => ['طباعة'],
	'_ADD_' => ['اضافة'],
	'_DELETE_' => ['حذف'],
	'_ERROR_OCCURRED_' => ['حدث خطأ, يرجى اعادة المحاولة لاحقاً'],
	'_AM_' => ['صباحاً', 'AM', 'Ö.Ö'],
	'_PM_' => ['مساءً', 'PM', 'Ö.S'],
	'_STATUS_CHANGED_' => ['تم تغيير الحالة'],
	'_GENERAL_ADMIN_' => ['مدير عام'],
	'_READ_MORE_' => ['المزيد', 'More'],
	'_404_' => ['الصفحة التي قمت بطلبها غير موجودة', 'The Page you were looking for, couldn\'t be found', 'Aradığınız sayfa bulunamadı'],
	'_BACK_TO_HOME_' => ['الرجوع إلى الرئيسية', 'Back to Home'],
	'_LANGUAGE_' => ['اللغة', 'Language', 'Dil'],
	'_SEND_' => ['إرسال', 'Send', 'Gönder'],
];

foreach($langs as $key => $value){
	define($key, $value[$_SESSION['lang']]);
}